name: flutter_boilerplate
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_db_store: ^4.1.1
  dio_cookie_manager: ^2.0.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  sqflite: ^2.2.8+1
  provider: ^6.0.5
  go_router: ^7.0.0
  flutter_screenutil: ^5.7.0
  logger: ^1.3.0
  path_provider: ^2.0.14
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  collection: ^1.16.0
  webview_flutter: ^3.0.4
  extended_image: ^6.3.0
  carousel_slider: ^4.1.1
  uuid: ^3.0.5
  pretty_json: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

